-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.audi_logs
(
    log_id serial NOT NULL,
    CONSTRAINT audi_logs_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.directions
(
    direction_id serial NOT NULL,
    CONSTRAINT directions_pkey PRIMARY KEY (direction_id)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
    id serial NOT NULL,
    warehouse_id uuid NOT NULL,
    products_variant_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    order_item_id uuid NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id uuid NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id uuid NOT NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    slug character varying(20) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default" NOT NULL,
    trade_mark text COLLATE pg_catalog."default" NOT NULL,
    model character varying(50) COLLATE pg_catalog."default",
    img_url text COLLATE pg_catalog."default" NOT NULL,
    video_url text COLLATE pg_catalog."default",
    type_product producttype NOT NULL,
    weight text COLLATE pg_catalog."default",
    dimensions text COLLATE pg_catalog."default",
    create_at timestamp without time zone DEFAULT now(),
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.rols
(
    rol_id serial NOT NULL,
    rol text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT rols_pkey PRIMARY KEY (rol_id),
    CONSTRAINT rols_rol_key UNIQUE (rol)
);

CREATE TABLE IF NOT EXISTS public.styles_products
(
    style_product_id serial NOT NULL,
    color text COLLATE pg_catalog."default" NOT NULL,
    size text COLLATE pg_catalog."default",
    material text COLLATE pg_catalog."default",
    capacity text COLLATE pg_catalog."default",
    version character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT styles_products_pkey PRIMARY KEY (style_product_id)
);

CREATE TABLE IF NOT EXISTS public.user_rols
(
    user_rol_id serial NOT NULL,
    user_id uuid NOT NULL,
    rol_id integer NOT NULL,
    CONSTRAINT user_rols_pkey PRIMARY KEY (user_rol_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying(25) COLLATE pg_catalog."default" NOT NULL,
    username character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cellphone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.warehouses
(
    warehouse_id uuid NOT NULL DEFAULT gen_random_uuid(),
    direction_id integer NOT NULL,
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    type_warehouse typewarehouse NOT NULL,
    CONSTRAINT warehouses_pkey PRIMARY KEY (warehouse_id)
);
END;