-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.courses
(
    course_id integer NOT NULL DEFAULT nextval('courses_id_seq'::regclass),
    title character varying(20) COLLATE pg_catalog."default" NOT NULL,
    descriptcion text COLLATE pg_catalog."default",
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT courses_pkey PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public.inscriptions
(
    user_id uuid NOT NULL,
    course_id integer NOT NULL,
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT inscriptions_pkey PRIMARY KEY (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS public.lessons
(
    lesson_id integer NOT NULL DEFAULT nextval('lessons_id_seq'::regclass),
    title text COLLATE pg_catalog."default" NOT NULL,
    order_lesson integer NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    course_id integer NOT NULL,
    CONSTRAINT lessons_pkey PRIMARY KEY (lesson_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id uuid NOT NULL DEFAULT gen_random_uuid(),
    amount numeric(10, 2) NOT NULL,
    currency currency NOT NULL,
    status status NOT NULL,
    paid_at timestamp without time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    course_id integer NOT NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.progress
(
    user_id uuid NOT NULL,
    lesson_id integer NOT NULL,
    complete_datetime timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_progress_pkey PRIMARY KEY (user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    rating integer NOT NULL,
    comment text COLLATE pg_catalog."default",
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    course_id integer NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS public.rols
(
    role_id serial NOT NULL,
    name rol NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT rols_pkey PRIMARY KEY (role_id),
    CONSTRAINT rols_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.users_rols
(
    user_id uuid NOT NULL,
    role_id serial NOT NULL,
    CONSTRAINT users_rols_pkey PRIMARY KEY (user_id, role_id)
);

ALTER TABLE IF EXISTS public.inscriptions
    ADD CONSTRAINT fk_inscriptions_courses FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inscriptions
    ADD CONSTRAINT fk_inscriptions_users FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lessons
    ADD CONSTRAINT fk_courses_lessons FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fk_payments_course FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fk_payments_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.progress
    ADD CONSTRAINT fk_progress_lesson FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (lesson_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.progress
    ADD CONSTRAINT fk_progress_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fk_reviews_courses FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fk_reviews_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users_rols
    ADD CONSTRAINT fk_users_rols_rol FOREIGN KEY (role_id)
    REFERENCES public.rols (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.users_rols
    ADD CONSTRAINT fk_users_rols_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;